import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { CodeBlock } from "@/components/docs/CodeBlock";
import { DocsDownloadActions } from "@/components/docs/DocsDownloadActions";
import { Callout } from "@/components/docs/Callout";

const groups: { resource: string; events: { name: string; desc: string }[] }[] = [
  {
    resource: "Payments",
    events: [
      { name: "payment.created", desc: "A transaction row was inserted (status=pending)." },
      { name: "payment.requires_action", desc: "3DS challenge or APM redirect required from the customer." },
      { name: "payment.processing", desc: "Acquirer has authorised; awaiting capture/settlement." },
      { name: "payment.completed", desc: "Funds captured. Transaction status flipped to completed." },
      { name: "payment.failed", desc: "Authorisation or capture declined. metadata.last_error contains the reason." },
      { name: "payment.canceled", desc: "An authorised payment was voided before capture." },
    ],
  },
  {
    resource: "Refunds",
    events: [
      { name: "refund.created", desc: "A refund row was inserted." },
      { name: "refund.completed", desc: "Acquirer cleared the refund." },
      { name: "refund.failed", desc: "Refund could not be processed; balance unaffected." },
    ],
  },
  {
    resource: "Payouts",
    events: [
      { name: "payout.created", desc: "A payout was queued for the next settlement window." },
      { name: "payout.in_transit", desc: "Submitted to SEPA / SWIFT / ACH / FPS / on-chain rail." },
      { name: "payout.completed", desc: "Funds confirmed in the destination account." },
      { name: "payout.failed", desc: "Rail rejected the payout — see metadata.rail_error." },
    ],
  },
  {
    resource: "Disputes",
    events: [
      { name: "dispute.created", desc: "Chargeback or retrieval request opened (synced from Chargeflow)." },
      { name: "dispute.updated", desc: "Network state, evidence_due_date, or outcome changed." },
      { name: "dispute.won", desc: "Decided in your favour; debit reversed." },
      { name: "dispute.lost", desc: "Decided against you; debit remains and a fee may be assessed." },
    ],
  },
  {
    resource: "Customers",
    events: [
      { name: "customer.created", desc: "New row inserted in customers." },
      { name: "customer.updated", desc: "Customer fields changed." },
      { name: "customer.deleted", desc: "Customer row was removed (cascade-deletes invoices/subscriptions)." },
    ],
  },
  {
    resource: "Subscriptions",
    events: [
      { name: "subscription.created", desc: "Subscription started (status=active or trialing)." },
      { name: "subscription.updated", desc: "Plan, payment method, or schedule changed." },
      { name: "subscription.trial_will_end", desc: "Fires 3 days before trial conversion." },
      { name: "subscription.renewed", desc: "Recurring charge succeeded." },
      { name: "subscription.past_due", desc: "Renewal failed; smart-retry engaged via retry-payment." },
      { name: "subscription.canceled", desc: "Subscription is no longer active." },
    ],
  },
  {
    resource: "Invoices",
    events: [
      { name: "invoice.created", desc: "Draft or open invoice issued." },
      { name: "invoice.sent", desc: "Hosted invoice email delivered." },
      { name: "invoice.paid", desc: "Invoice fully paid; status=paid." },
      { name: "invoice.overdue", desc: "Detected by invoice-overdue-check (runs daily)." },
      { name: "invoice.voided", desc: "Invoice canceled." },
    ],
  },
  {
    resource: "Open Banking",
    events: [
      { name: "open_banking.payment.created", desc: "PIS request issued to the ASPSP." },
      { name: "open_banking.payment.authorised", desc: "Customer completed strong customer authentication." },
      { name: "open_banking.payment.completed", desc: "Funds settled (FPS / SEPA Instant)." },
      { name: "open_banking.payment.failed", desc: "Customer abandoned or bank rejected." },
      { name: "open_banking.refund.completed", desc: "Bank-rail refund cleared." },
    ],
  },
  {
    resource: "Crypto",
    events: [
      { name: "crypto.charge.created", desc: "Deposit address generated by crypto-pay." },
      { name: "crypto.charge.detected", desc: "On-chain transaction observed (0 confirmations)." },
      { name: "crypto.charge.confirmed", desc: "Required confirmations reached; status=complete." },
      { name: "crypto.charge.expired", desc: "Window closed without sufficient funds." },
      { name: "crypto.withdrawal.broadcast", desc: "Withdrawal sent to the network." },
      { name: "crypto.withdrawal.confirmed", desc: "Withdrawal mined and confirmed." },
    ],
  },
  {
    resource: "Payment Links",
    events: [
      { name: "payment_link.created", desc: "Hosted checkout link issued." },
      { name: "payment_link.completed", desc: "Customer completed checkout via the link." },
      { name: "payment_link.expired", desc: "Link expired without payment." },
    ],
  },
];

export default function DocsWebhookEvents() {
  return (
    <div className="max-w-4xl mx-auto space-y-10">
      <div className="flex items-start justify-between gap-4 flex-wrap">
        <div>
          <Badge variant="secondary" className="mb-3">Reference</Badge>
          <h1 className="text-3xl font-heading font-bold tracking-tight">Webhook Events</h1>
          <p className="text-muted-foreground mt-2">
            Every event MzzPay dispatches via <code>webhook-dispatch</code>, grouped by
            resource. Subscribe in <strong>Settings → Webhooks</strong> or by inserting into
            the <code>webhook_endpoints</code> table.
          </p>
        </div>
        <DocsDownloadActions />
      </div>

      <Callout variant="info" title="One envelope, every event">
        All webhooks share the envelope below. The <code>type</code> field identifies the
        event; <code>data</code> contains the resource snapshot at dispatch time. Verify the{" "}
        <code>X-Mzzpay-Signature</code> header — it is the raw HMAC-SHA256 hex digest of the
        request body using your endpoint secret.
      </Callout>

      <Card>
        <CardHeader>
          <CardTitle className="text-lg">Webhook Envelope</CardTitle>
        </CardHeader>
        <CardContent>
          <CodeBlock
            code={`POST /your/endpoint
Content-Type: application/json
X-Mzzpay-Event: payment.completed
X-Mzzpay-Signature: 7c9f3a1b8d4e2c5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f

{
  "id": "4f5a6b7c-8d9e-0a1b-2c3d-4e5f6a7b8c9d",
  "type": "payment.completed",
  "created": 1714032840000,
  "data": {
    "id": "9b1c2d3e-4f5a-6b7c-8d9e-0a1b2c3d4e5f",
    "amount": 5000,
    "currency": "usd",
    "status": "completed",
    "merchant_id": "mer_abc123"
  }
}`}
            language="curl"
          />
        </CardContent>
      </Card>

      {groups.map((g) => (
        <Card key={g.resource}>
          <CardHeader>
            <CardTitle className="text-lg">{g.resource}</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="border border-border rounded-lg overflow-hidden divide-y divide-border">
              {g.events.map((e) => (
                <div key={e.name} className="grid grid-cols-[260px_1fr] gap-4 px-4 py-3 text-sm">
                  <code className="text-xs font-mono font-semibold text-primary self-start">
                    {e.name}
                  </code>
                  <p className="text-muted-foreground text-[13px] leading-relaxed">{e.desc}</p>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      ))}
    </div>
  );
}
