project_id = "ccqiuoilfvuetajyjyiv"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.chargeflow-webhook]
    verify_jwt = false
  [functions.send-transactional-email]
    verify_jwt = false
