project_id = "sprjfzeyyihtfvxnfuhb"

[functions.newsletter-subscribe]
verify_jwt = false

[functions.crypto-pay]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true

[functions.email-rpc-test]
verify_jwt = false

[functions.checkout-host-status]
verify_jwt = false

[functions.card-test-runner]
verify_jwt = false
